package common

const (
	EntryKeyPostgres = "postgres"
	EntryKeyMysql    = "mysql"
	EntryKeyMongodb  = "mongodb"
)

// Define constants for HTTP header names
const (
	HeaderAccept                        = "Accept"
	HeaderAcceptCharset                 = "Accept-Charset"
	HeaderAcceptEncoding                = "Accept-Encoding"
	HeaderAcceptLanguage                = "Accept-Language"
	HeaderAuthorization                 = "Authorization"
	HeaderCacheControl                  = "Cache-Control"
	HeaderContentDisposition            = "Content-Disposition"
	HeaderContentEncoding               = "Content-Encoding"
	HeaderContentLength                 = "Content-Length"
	HeaderContentType                   = "Content-Type"
	HeaderCookie                        = "Cookie"
	HeaderHost                          = "Host"
	HeaderOrigin                        = "Origin"
	HeaderReferer                       = "Referer"
	HeaderUserAgent                     = "User-Agent"
	HeaderIfMatch                       = "If-Match"
	HeaderIfNoneMatch                   = "If-None-Match"
	HeaderETag                          = "ETag"
	HeaderLastModified                  = "Last-Modified"
	HeaderLocation                      = "Location"
	HeaderPragma                        = "Pragma"
	HeaderRetryAfter                    = "Retry-After"
	HeaderServer                        = "Server"
	HeaderWWWAuthenticate               = "WWW-Authenticate"
	HeaderDate                          = "Date"
	HeaderExpires                       = "Expires"
	HeaderAge                           = "Age"
	HeaderConnection                    = "Connection"
	HeaderContentLanguage               = "Content-Language"
	HeaderForwarded                     = "Forwarded"
	HeaderIfModifiedSince               = "If-Modified-Since"
	HeaderUpgrade                       = "Upgrade"
	HeaderVia                           = "Via"
	HeaderWarning                       = "Warning"
	HeaderXForwardedFor                 = "X-Forwarded-For"
	HeaderXForwardedHost                = "X-Forwarded-Host"
	HeaderXForwardedProto               = "X-Forwarded-Proto"
	HeaderXRequestedWith                = "X-Requested-With"
	HeaderXFrameOptions                 = "X-Frame-Options"
	HeaderXXSSProtection                = "X-XSS-Protection"
	HeaderXContentTypeOpts              = "X-Content-Type-Options"
	HeaderContentSecurity               = "Content-Security-Policy"
	HeaderStrictTransport               = "Strict-Transport-Security"
	HeaderPublicKeyPins                 = "Public-Key-Pins"
	HeaderExpectCT                      = "Expect-CT"
	HeaderAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	HeaderAccessControlAllowMethods     = "Access-Control-Allow-Methods"
	HeaderAccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	HeaderAccessControlMaxAge           = "Access-Control-Max-Age"
	HeaderAccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	HeaderAccessControlRequestMethod    = "Access-Control-Request-Method"
	HeaderAccessControlRequestHeaders   = "Access-Control-Request-Headers"
	HeaderAcceptPatch                   = "Accept-Patch"
	HeaderDeltaBase                     = "Delta-Base"
	HeaderIfUnmodifiedSince             = "If-Unmodified-Since"
	HeaderAcceptRanges                  = "Accept-Ranges"
	HeaderContentRange                  = "Content-Range"
	HeaderAllow                         = "Allow"
	HeaderAccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	HeaderXCSRFToken                    = "X-CSRF-Token"
	HeaderXRealIP                       = "X-Real-IP"
	HeaderContentSecurityPolicy         = "Content-Security-Policy"
	HeaderReferrerPolicy                = "Referrer-Policy"
	HeaderExpectCt                      = "Expect-CT"
	HeaderStrictTransportSecurity       = "Strict-Transport-Security"
	HeaderUpgradeInsecureRequests       = "Upgrade-Insecure-Requests"
)

// Define constants for media types
const (
	MediaTypeApplicationJSON         = "application/json"
	MediaTypeApplicationXML          = "application/xml"
	MediaTypeApplicationForm         = "application/x-www-form-urlencoded"
	MediaTypeApplicationOctetStream  = "application/octet-stream"
	MediaTypeTextPlain               = "text/plain"
	MediaTypeTextHTML                = "text/html"
	MediaTypeImageJPEG               = "image/jpeg"
	MediaTypeImagePNG                = "image/png"
	MediaTypeImageGIF                = "image/gif"
	MediaTypeAudioMP3                = "audio/mpeg"
	MediaTypeAudioWAV                = "audio/wav"
	MediaTypeVideoMP4                = "video/mp4"
	MediaTypeVideoAVI                = "video/x-msvideo"
	MediaTypeApplicationPDF          = "application/pdf"
	MediaTypeApplicationMSWord       = "application/msword"
	MediaTypeApplicationMSPowerPoint = "application/vnd.ms-powerpoint"
	MediaTypeApplicationExcel        = "application/vnd.ms-excel"
	MediaTypeApplicationZip          = "application/zip"
	MediaTypeApplicationGzip         = "application/gzip"
	MediaTypeMultipartFormData       = "multipart/form-data"
	MediaTypeImageBMP                = "image/bmp"
	MediaTypeImageTIFF               = "image/tiff"
	MediaTypeTextCSS                 = "text/css"
	MediaTypeTextJavaScript          = "text/javascript"
	MediaTypeApplicationJSONLD       = "application/ld+json"
	MediaTypeApplicationRDFXML       = "application/rdf+xml"
	MediaTypeApplicationGeoJSON      = "application/geo+json"
	MediaTypeApplicationMsgpack      = "application/msgpack"
	MediaTypeApplicationOgg          = "application/ogg"
	MediaTypeApplicationGraphQL      = "application/graphql"
	MediaTypeApplicationProtobuf     = "application/protobuf"
	MediaTypeImageWebP               = "image/webp"
	MediaTypeFontWOFF                = "font/woff"
	MediaTypeFontWOFF2               = "font/woff2"
	MediaTypeAudioFLAC               = "audio/flac"
	MediaTypeVideoWebM               = "video/webm"
	MediaTypeApplicationDart         = "application/dart"
	MediaTypeApplicationXLSX         = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	MediaTypeApplicationPPTX         = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	MediaTypeApplicationGRPC         = "application/grpc"
)
